### ISSUE TITLE
[Craft 5] Getting unknown property: craft\elements\User::contentId

### ISSUE THREAD

**Issue by Tam** [c10d-dev/craft-recaptcha#6]
I'm getting this error when the recaptcha is attached to the register form:

```
yii\base\UnknownPropertyException: Getting unknown property: craft\elements\User::contentId in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2265): yii\base\Component->__get('contentId')
#1 /var/www/html/vendor/c10d/craft-recaptcha/src/CraftRecaptcha.php(152): craft\base\Element->__get('contentId')
#2 [internal function]: c10d\craftrecaptcha\CraftRecaptcha->c10d\craftrecaptcha\{closure}(Object(yii\base\ModelEvent))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\ModelEvent))
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'beforeValidate', Object(yii\base\ModelEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Model.php(386): yii\base\Component->trigger('beforeValidate', Object(yii\base\ModelEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Model.php(351): yii\base\Model->beforeValidate()
#7 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2590): yii\base\Model->validate(NULL, false)
#8 /var/www/html/vendor/craftcms/cms/src/controllers/UsersController.php(1648): craft\base\Element->validate(NULL, false)
#9 [internal function]: craft\controllers\UsersController->actionSaveUser()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-user', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('users/save-user', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction('users/save-user', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/web/index.php(12): yii\base\Application->run()
#18 {main}
```

**Comment by c10d-dev** [comment]
Hello!
Sorry about that, I've updated the plugin, please test the v3.0.1 and tell me if it works now!

**Comment by Tam** [comment]
Looks good, ta 👍
